implement design
webprogramminghack/class1 pull request #5
Opened 2024-07-24 11:49 UTC by supriadiacep

2024-07-25 04:03 UTC, webprogramminghack requested changes

2024-07-25 04:03 UTC, webprogramminghack commented on index.html
> +          <form class="form">
Masukkan ke dalam `<div class="content">`

2024-07-25 04:03 UTC, webprogramminghack commented on index.html
> +            <div class="btnsend">
Button tidak perlu dimasukkan ke dalam `<div>` (itemnya hanya 1)

2024-07-25 04:03 UTC, webprogramminghack commented on index.html
> +              <input
Pakai type="tel"

2024-07-25 04:03 UTC, webprogramminghack commented on index.html
> +              <li>Home</li>
Di dalam list harus ada a. nav>ul>li>a

2024-07-26 06:25 UTC, supriadiacep commented on index.html
> +          <form class="form">
jadi class = "header" dan class = "form" dibungkus ke class="content" ?

2024-07-26 17:15 UTC, webprogramminghack commented
Nice!

2024-07-26 17:15 UTC, closed without merging